// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b5e11fea-4178-457e-b1a1-5d1371b9a114",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_MZm6tbN8q",
    "aws_user_pools_web_client_id": "17gpsuo5m4igqbi2e7lnbq899b",
    "oauth": {}
};


export default awsmobile;
