// API URL
export const API = "https://4b7jtysje3.execute-api.us-east-1.amazonaws.com/develop";
export const WSS = "wss://j1g49nfi28.execute-api.us-east-1.amazonaws.com/dev";

// User Types
export const SET_FIRST_NAME = 'SET_FIRST_NAME';
export const GET_USER = 'GET_USER';
export const POST_USER = 'POST_USER';
export const GET_USER_COMPLETE = 'GET_USER_COMPLETE';
export const POST_USER_COMPLETE = 'POST_USER_COMPLETE';
export const GET_GROUP_BY_USER = 'GET_GROUP_BY_USER';
export const GET_GROUP_BY_USER_COMPLETE = 'GET_GROUP_BY_USER_COMPLETE';

// Group Types
export const JOIN_GROUP = 'JOIN_GROUP';
export const JOIN_GROUP_COMPLETE = 'JOIN_GROUP_COMPLETE';

// New Group Types
export const ADD_GROUP = 'ADD_GROUP';
export const POST_GROUP = 'POST_GROUP';
export const UPDATE_SUBJECT_ON_NEW_GROUP = 'UPDATE_SUBJECT_ON_NEW_GROUP';
export const UPDATE_SUBJECT_ID_ON_NEW_GROUP = 'UPDATE_SUBJECT_ID_ON_NEW_GROUP';
export const UPDATE_UNIVERSITY_ON_NEW_GROUP = 'UPDATE_UNIVERSITY_ON_NEW_GROUP';
export const UPDATE_NAME_ON_NEW_GROUP = 'UPDATE_NAME_ON_NEW_GROUP';
export const UPDATE_START_DATE_ON_NEW_GROUP = 'UPDATE_START_DATE_ON_NEW_GROUP';
export const UPDATE_END_DATE_ON_NEW_GROUP = 'UPDATE_END_DATE_ON_NEW_GROUP';
export const NEW_GROUP_START_DATE_SELECTED = 'NEW_GROUP_START_DATE_SELECTED';
export const NEW_GROUP_END_DATE_SELECTED = 'NEW_GROUP_END_DATE_SELECTED';
export const UPDATE_UNIVERSITY = 'UPDATE_UNIVERSITY';
export const UPDATE_START_DATE = 'UPDATE_START_DATE';
export const UPDATE_END_DATE = 'UPDATE_END_DATE';
export const GET_CLASSES = 'GET_CLASSES';

// Group Search Types
export const ADD_RESULT = 'ADD_RESULT';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const RESTRICT_TO_UNIVERSITY = 'RESTRICT_TO_UNIVERSITY';
export const GET_GROUP_RESULTS = 'GET_GROUP_RESULTS';
export const GET_GROUP_RESULTS_COMPLETE = 'GET_GROUP_RESULTS_COMPLETE';
export const SET_DETAILS = 'SET_DETAILS';


// Web Socket Types
export const CONNECT = 'CONNECT';
export const DISCONNECT = 'DISCONNECT';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MSG_RECEIVED = 'MSG_RECEIVED';


// Form Types
export const FORM_CHANGE = {
    REGISTER: 'REGISTER_FORM_CHANGE',
    SIGNIN: 'SIGNIN_FORM_CHANGE',
}
export const FORM_SUBMIT = {
    REGISTER: 'REGISTER_FORM_SUBMIT',
    REGISTER_POST: 'REGISTER_POST',
    SIGNIN: 'SIGNIN_FORM_SUBMIT',
    GET_USERID: 'GET_USER_ID',
    GET_USERID_COMPLETE: 'GET_USER_ID_COMPLETE',
    REGISTER_MODAL_VISIBILITY: 'REGISTER_FORM_MODAL_VISIBILITY'
}
