// API URL
export const API = "https://bs4epgtlhf.execute-api.us-east-2.amazonaws.com/dev";
export const WSS = "wss://0xj242xk57.execute-api.us-east-2.amazonaws.com/dev";

// User Types
export const SET_FIRST_NAME = 'SET_FIRST_NAME';
export const GET_USER = 'GET_USER';
export const POST_USER = 'POST_USER';
export const GET_USER_COMPLETE = 'GET_USER_COMPLETE';
export const POST_USER_COMPLETE = 'POST_USER_COMPLETE';
export const GET_GROUP_BY_USER = 'GET_GROUP_BY_USER';
export const GET_GROUP_BY_USER_COMPLETE = 'GET_GROUP_BY_USER_COMPLETE';
export const GET_GROUPS_BY_EMAIL = 'GET_GROUPS_BY_EMAIL';
export const GET_GROUPS_BY_EMAIL_COMPLETE = 'GET_GROUPS_BY_EMAIL_COMPLETE';

// Group Types
export const JOIN_GROUP = 'JOIN_GROUP';
export const JOIN_GROUP_COMPLETE = 'JOIN_GROUP_COMPLETE';
export const GROUP_SELECTED = 'GROUP_SELECTED';
export const CLEAR_GROUPS = 'CLEAR_GROUPS';

// New Group Types
export const ADD_GROUP = 'ADD_GROUP';
export const POST_GROUP = 'POST_GROUP';
export const UPDATE_SUBJECT_ON_NEW_GROUP = 'UPDATE_SUBJECT_ON_NEW_GROUP';
export const UPDATE_SUBJECT_ID_ON_NEW_GROUP = 'UPDATE_SUBJECT_ID_ON_NEW_GROUP';
export const UPDATE_UNIVERSITY_ON_NEW_GROUP = 'UPDATE_UNIVERSITY_ON_NEW_GROUP';
export const UPDATE_NAME_ON_NEW_GROUP = 'UPDATE_NAME_ON_NEW_GROUP';
export const UPDATE_START_DATE_ON_NEW_GROUP = 'UPDATE_START_DATE_ON_NEW_GROUP';
export const UPDATE_END_DATE_ON_NEW_GROUP = 'UPDATE_END_DATE_ON_NEW_GROUP';
export const NEW_GROUP_START_DATE_SELECTED = 'NEW_GROUP_START_DATE_SELECTED';
export const NEW_GROUP_END_DATE_SELECTED = 'NEW_GROUP_END_DATE_SELECTED';
export const UPDATE_UNIVERSITY = 'UPDATE_UNIVERSITY';
export const UPDATE_START_DATE = 'UPDATE_START_DATE';
export const UPDATE_END_DATE = 'UPDATE_END_DATE';
export const GET_CLASSES = 'GET_CLASSES';

// Group Search Types
export const ADD_RESULT = 'ADD_RESULT';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const RESTRICT_TO_UNIVERSITY = 'RESTRICT_TO_UNIVERSITY';
export const GET_GROUP_RESULTS = 'GET_GROUP_RESULTS';
export const GET_GROUP_RESULTS_COMPLETE = 'GET_GROUP_RESULTS_COMPLETE';
export const SET_DETAILS = 'SET_DETAILS';


// Web Socket Types
export const CONNECT = '$connect';
export const DISCONNECT = '$disconnect';
export const IDENTIFY = 'identify';
export const SEND_MESSAGE = 'sendmessage';
export const MSG_RECEIVED = 'MSG_RECEIVED';

// Message Types
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_COMPLETE = 'GET_MESSAGES_COMPLETE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';


// Form Types
export const FORM_CHANGE = {
    REGISTER: 'REGISTER_FORM_CHANGE',
    SIGNIN: 'SIGNIN_FORM_CHANGE',
}
export const FORM_SUBMIT = {
    REGISTER: 'REGISTER_FORM_SUBMIT',
    REGISTER_POST: 'REGISTER_POST',
    SIGNIN: 'SIGNIN_FORM_SUBMIT',
    GET_USERID: 'GET_USER_ID',
    GET_USERID_COMPLETE: 'GET_USER_ID_COMPLETE',
    REGISTER_MODAL_VISIBILITY: 'REGISTER_FORM_MODAL_VISIBILITY'
}
